// =====================================================================
//  Euroleague Hub — simple single-page app (no build step, no libraries)
//  Data comes from js/data.js, generated by update_data.py.
//  Pages are selected by the URL hash: #home, #standings, #stats,
//  #teams, #team/MAD, #schedule, #game/27, #predictions, #bets (js/betting.js)
// =====================================================================


// ---------- Prepare data ----------
const teamById = {};
const players = [];
TEAMS.forEach(team => {
  teamById[team.id] = team;
  team.players.forEach(p => {
    p.team = team.id;
    const [m2, a2, m3, a3, mf, af] = p.sh || [0, 0, 0, 0, 0, 0];
    p.p2 = a2 ? 100 * m2 / a2 : null;
    p.p3 = a3 ? 100 * m3 / a3 : null;
    p.ft = af ? 100 * mf / af : null;
    players.push(p);
  });
});
const gameByCode = {};
GAMES.forEach(g => { gameByCode[g.code] = g; });

const played = GAMES.filter(g => g.score);
const upcoming = GAMES.filter(g => !g.score);

// ---------- Language: English (default) or Lithuanian, chosen in the header ----------
let LANG = "en";
try { if (localStorage.getItem("lang") === "lt") LANG = "lt"; } catch { /* no storage: English */ }
const L = (en, lt) => (LANG === "lt" ? lt : en);
const NAV = {
  home: ["Home", "Pradžia"], standings: ["Standings", "Lentelė"], stats: ["Stats", "Statistika"],
  teams: ["Teams", "Komandos"], schedule: ["Schedule", "Tvarkaraštis"], predictions: ["Predictions", "Prognozės"],
  bets: ["Betting", "Statymai"], ticket: ["Ticket", "Bilietas"],
};
function applyLanguage() {
  document.documentElement.lang = LANG;
  document.querySelectorAll("nav a").forEach(a => { if (NAV[a.dataset.nav]) a.textContent = L(...NAV[a.dataset.nav]); });
  document.querySelectorAll("[data-lang]").forEach(b => b.classList.toggle("active", b.dataset.lang === LANG));
  document.getElementById("footerText").innerHTML = L(
    `Data: official EuroLeague API · updated ${esc(UPDATED)} · run <code>python update_data.py</code> to refresh.
     Not affiliated with EuroLeague Basketball.`,
    `Duomenys: oficialus EuroLeague API · atnaujinta ${esc(UPDATED)} · atnaujinti: <code>python update_data.py</code>.
     Nesusijęs su EuroLeague Basketball.`);
}
function setLanguage(lang) {
  LANG = lang;
  try { localStorage.setItem("lang", lang); } catch { /* only for this visit */ }
  applyLanguage();
  route();
}

// ---------- Helpers ----------
const $app = document.getElementById("app");
const esc = s => String(s ?? "").replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const LT_DAYS = ["sk", "pr", "an", "tr", "kt", "pn", "št"];
const LT_MONTHS = ["saus.", "vas.", "kov.", "bal.", "geg.", "birž.", "liep.", "rugp.", "rugs.", "spal.", "lapkr.", "gruod."];
const fmtDate = d => {
  const date = new Date(d.slice(0, 10) + "T12:00:00");
  return LANG === "lt"
    ? `${LT_DAYS[date.getDay()]}, ${LT_MONTHS[date.getMonth()]} ${date.getDate()} d.`
    : date.toLocaleDateString("en-GB", { weekday: "short", day: "numeric", month: "short" });
};
const fmtTime = d => d.slice(11, 16);
const signed = n => (n > 0 ? "+" : "") + n;
const signed1 = n => (n > 0 ? "+" : "") + Number(n).toFixed(1); // always one decimal
const num = (n, key) => key === "gp" ? n : Number(n).toFixed(1);

function badge(team, size = "") {
  return team.crest
    ? `<img class="crest ${size}" src="${esc(team.crest)}" alt="${esc(team.short)}" loading="lazy">`
    : `<span class="badge ${size}">${esc(team.short)}</span>`;
}
function teamLink(id, size = "sm") {
  const t = teamById[id];
  return `<a class="team-cell" href="#team/${t.id}">${badge(t, size)}<span>${esc(t.name)}</span></a>`;
}

// ---------- Standings ----------
function computeStandings() {
  const rows = {};
  TEAMS.forEach(t => rows[t.id] = { id: t.id, gp: 0, w: 0, l: 0, pf: 0, pa: 0, form: [], home: [0, 0], away: [0, 0] });

  played.filter(g => !g.phase).forEach(g => { // regular season only
    const [hs, as] = g.score;
    const h = rows[g.home], a = rows[g.away];
    h.home[hs > as ? 0 : 1]++; a.away[as > hs ? 0 : 1]++;
    h.gp++; a.gp++;
    h.pf += hs; h.pa += as;
    a.pf += as; a.pa += hs;
    if (hs > as) { h.w++; a.l++; h.form.push("W"); a.form.push("L"); }
    else { a.w++; h.l++; a.form.push("W"); h.form.push("L"); }
  });

  const list = Object.values(rows)
    .map(r => ({ ...r, diff: r.pf - r.pa, form: r.form.slice(-5) }))
    .sort((a, b) => b.w - a.w || b.diff - a.diff || b.pf - a.pf);
  // Use the official EuroLeague order (it applies head-to-head tie-breakers), as long as it was made
  // from the same results as the ones shown here.
  const off = typeof OFFICIAL !== "undefined" && OFFICIAL && OFFICIAL.teams;
  if (off && list.every(r => off[r.id] && off[r.id][1] === r.gp && off[r.id][2] === r.w))
    list.sort((a, b) => off[a.id][0] - off[b.id][0]);
  return list;
}

function standingsTable(rows, compact = false) {
  return `
    <div class="table-wrap"><table>
      <thead><tr>
        <th>#</th><th class="left">${L("Team", "Komanda")}</th><th>${L("GP", "R")}</th><th>${L("W", "P")}</th><th>${L("L", "Pr")}</th>
        ${compact ? "" : `<th>${L("Home", "Namie")}</th><th>${L("Away", "Išvykoje")}</th><th>${L("PF", "ĮT")}</th><th>${L("PA", "PT")}</th>`}<th>+/-</th>${compact ? "" : `<th>${L("Form", "Forma")}</th>`}
      </tr></thead>
      <tbody>
        ${rows.map((r, i) => `
          <tr class="${i < 6 ? "playoff" : i < 10 ? "playin" : ""}">
            <td class="pos">${i + 1}</td>
            <td class="left">${teamLink(r.id)}</td>
            <td>${r.gp}</td><td>${r.w}</td><td>${r.l}</td>
            ${compact ? "" : `<td>${r.home.join("–")}</td><td>${r.away.join("–")}</td><td>${r.pf}</td><td>${r.pa}</td>`}
            <td class="${r.diff > 0 ? "plus" : r.diff < 0 ? "minus" : ""}">${signed(r.diff)}</td>
            ${compact ? "" : `<td><span class="form">${r.form.map(f => `<b class="${f}">${f}</b>`).join("")}</span></td>`}
          </tr>`).join("")}
      </tbody>
    </table></div>
    <div class="legend"><span class="l-po">${L("Playoffs (1–6)", "Atkrintamosios (1–6)")}</span><span class="l-pi">Play-In (7–10)</span></div>`;
}

// ---------- Season forecast ----------
// MODEL.forecast (model.simulate_season): team -> [P(finish 1-6), P(finish 7-10), expected final wins]
function seasonForecast() {
  const f = MODEL.forecast;
  if (!f || !upcoming.some(g => !g.phase)) return "";
  const now = Object.fromEntries(computeStandings().map(r => [r.id, r]));
  const ids = Object.keys(f).sort((a, b) => f[b][2] - f[a][2]);
  const pct = p => (p >= 0.995 ? ">99%" : p < 0.005 ? "<1%" : `${Math.round(100 * p)}%`);
  const bar = (p, cls) => `<td class="fc"><span class="fc-bar ${cls}" style="width:${Math.round(100 * p)}%"></span><span class="fc-num">${pct(p)}</span></td>`;
  return `<div class="card">
    <h2>${L("Season forecast", "Sezono prognozė")}</h2>
    <div class="table-wrap"><table>
      <thead><tr>
        <th>#</th><th class="left">${L("Team", "Komanda")}</th><th>${L("Now", "Dabar")}</th>
        <th>${L("Expected wins", "Tikėtinos pergalės")}</th>
        <th>${L("Playoffs (1–6)", "Atkrintamosios (1–6)")}</th><th>Play-In (7–10)</th><th>${L("Top 10", "Dešimtukas")}</th>
      </tr></thead>
      <tbody>${ids.map((id, i) => `<tr>
        <td class="pos">${i + 1}</td><td class="left">${teamLink(id)}</td>
        <td>${now[id].w}–${now[id].l}</td>
        <td><b>${f[id][2].toFixed(1)}</b> <span class="muted">/ ${MODEL.forecastGames}</span></td>
        ${bar(f[id][0], "po")}${bar(f[id][1], "pi")}
        <td>${pct(f[id][0] + f[id][1])}</td></tr>`).join("")}
      </tbody>
    </table></div>
    <p class="note">${L(
      `The rest of the regular season played out 10,000 times with the prediction model: how often each team finishes
       in the top 6 (straight to the playoffs) or 7th–10th (Play-In), and its average final number of wins. Tested on the
       last three seasons, forecasts like these were reliable: teams given 50–70% for the top 6 made it 62% of the
       time. Before round 5 the final win totals were still off by about 2.5 wins on average, so early in the season read
       these as rough chances. Injuries and transfers during the season are not known to the model.`,
      `Likusi reguliariojo sezono dalis sužaista 10 000 kartų su prognozių modeliu: kaip dažnai komanda užima 1–6 vietą
       (tiesiai į atkrintamąsias) ar 7–10 vietą („Play-In“) ir kiek vidutiniškai laimi rungtynių. Patikrinta su trimis
       praėjusiais sezonais: tokios prognozės pasitvirtino, pvz., komandos, kurioms duota 50–70 % patekti į šešetuką, pateko
       62 % atvejų. Prieš 5 turą galutinis pergalių skaičius dar skyrėsi vidutiniškai apie 2,5 pergalės, todėl sezono
       pradžioje tai tik apytikslės tikimybės. Traumų ir perėjimų sezono metu modelis nežino.`)}</p>
  </div>`;
}

// ---------- Predictions ----------
// Team ratings come from model.py (via update_data.py) — see the README for how they're made.
function predict(homeId, awayId, neutral = false) {
  const t = MODEL.teams, h = neutral ? 0 : MODEL.hca / 2;
  const homePts = MODEL.avg + h + t[homeId][0] + t[awayId][1];
  const awayPts = MODEL.avg - h + t[awayId][0] + t[homeId][1];
  const margin = homePts - awayPts;
  const homeWin = 1 / (1 + Math.exp(-margin / MODEL.scale));
  let hp = Math.round(homePts), ap = Math.round(awayPts);
  if (hp === ap) margin >= 0 ? hp++ : ap++; // basketball has no draws
  return { homePts: hp, awayPts: ap, homeWin, margin, total: homePts + awayPts };
}

// how the model did on games already played (each predicted before tip-off)
function predictionRecord(games = played) {
  const done = games.filter(g => g.pred);
  const right = done.filter(g => (g.pred[2] >= 0.5) === (g.score[0] > g.score[1])).length;
  return { right, total: done.length };
}

// Round-by-round history of the pre-game predictions, next to two simple yardsticks:
// always picking the home team, and the bookmaker's favourite where odds were published (js/odds.js).
function roundHistory() {
  const book = (typeof BOOK_ODDS !== "undefined" && BOOK_ODDS.games) || {};
  const homeWon = g => g.score[0] > g.score[1];
  const stats = games => {
    const right = games.filter(g => (g.pred[2] >= 0.5) === homeWon(g));
    const withOdds = games.filter(g => book[g.code] && book[g.code].ml && book[g.code].ml[0] !== book[g.code].ml[1]);
    const misses = games.filter(g => !right.includes(g)).sort((a, b) => Math.abs(b.pred[2] - 0.5) - Math.abs(a.pred[2] - 0.5));
    return {
      n: games.length, right: right.length,
      home: games.filter(homeWon).length,
      bookN: withOdds.length,
      bookRight: withOdds.filter(g => (book[g.code].ml[0] < book[g.code].ml[1]) === homeWon(g)).length,
      modelOnBook: withOdds.filter(g => (g.pred[2] >= 0.5) === homeWon(g)).length,
      err: games.reduce((s, g) => s + Math.abs(g.pred[0] - g.pred[1] - (g.score[0] - g.score[1])), 0) / games.length,
      worst: misses[0],
    };
  };
  const done = played.filter(g => g.pred);
  if (!done.length) return "";
  const rounds = [...new Set(done.map(g => g.round))].sort((a, b) => b - a);
  const frac = (a, b) => (b ? `${a}/${b}` : "–");
  const row = (label, s, cls = "") => `<tr class="${cls}">
    <td class="left">${label}</td>
    <td><b>${s.right}/${s.n}</b></td><td>${Math.round(100 * s.right / s.n)}%</td>
    <td>${s.home}/${s.n}</td>
    <td>${s.bookN ? `${frac(s.bookRight, s.bookN)} <span class="muted">(${L("model", "modelis")} ${frac(s.modelOnBook, s.bookN)})</span>` : "–"}</td>
    <td>${s.err.toFixed(1)}</td>
    <td class="left">${s.worst && cls !== "total" ? (() => {
      const g = s.worst, p = Math.max(g.pred[2], 1 - g.pred[2]);
      const fav = teamById[g.pred[2] >= 0.5 ? g.home : g.away], dog = teamById[g.pred[2] >= 0.5 ? g.away : g.home];
      return `<a href="#game/${g.code}">${esc(fav.name)} ${Math.round(100 * p)}%</a> <span class="muted">${L("lost to", "pralaimėjo prieš")} ${esc(dog.name)}</span>`;
    })() : ""}</td></tr>`;
  return `<div class="card">
    <h2>${L("Round by round", "Pagal turus")}</h2>
    <div class="table-wrap"><table>
      <thead><tr>
        <th class="left">${L("Round", "Turas")}</th><th>${L("Model right", "Modelis atspėjo")}</th><th>%</th>
        <th>${L("Home team won", "Laimėjo šeimininkai")}</th><th>${L("Bookmaker's favourite won", "Laimėjo lažybų favoritas")}</th>
        <th>${L("Margin error", "Skirtumo paklaida")}</th><th class="left">${L("Biggest miss", "Didžiausia klaida")}</th>
      </tr></thead>
      <tbody>
        ${rounds.map(r => row(L(`Round ${r}`, `${r} turas`), stats(done.filter(g => g.round === r)))).join("")}
        ${row(L("Season", "Sezonas"), stats(done), "total")}
      </tbody>
    </table></div>
    <p class="note">${L(
      `Margin error = average gap in points between the predicted and the real score difference. The bookmaker column
       only counts games whose odds were published on this site before the round; in brackets, the model on those same games.`,
      `Skirtumo paklaida = vidutinis taškų skirtumas tarp prognozuoto ir tikro rezultato skirtumo. Lažybų stulpelyje
       skaičiuojamos tik rungtynės, kurių koeficientai buvo paskelbti šioje svetainėje prieš turą; skliaustuose – modelis tose pačiose rungtynėse.`)}</p>
  </div>`;
}

function probBar(homeId, awayId, p) {
  const h = teamById[homeId], a = teamById[awayId];
  const hp = Math.round(p * 100), ap = 100 - hp;
  return `<div class="prob-bar">
    <div class="ph" style="width:${hp}%">${esc(h.short)} ${hp}%</div>
    <div class="pa" style="width:${ap}%">${ap}% ${esc(a.short)}</div>
  </div>`;
}

// ---------- Game rows ----------
function gameRow(g, showPrediction = false) {
  let middle, homeCls = "", awayCls = "";
  if (g.score) {
    const [hs, as] = g.score;
    homeCls = hs > as ? "winner" : "loser";
    awayCls = as > hs ? "winner" : "loser";
    middle = `${hs} – ${as}<small>${L("Final", "Baigta")} · ${fmtDate(g.date)}</small>`;
  } else if (showPrediction) {
    const p = predict(g.home, g.away, g.neutral);
    middle = `<span class="muted">${p.homePts} – ${p.awayPts}</span><small>${fmtDate(g.date)} · ${fmtTime(g.date)}</small>`;
  } else {
    middle = `vs<small>${fmtDate(g.date)} · ${fmtTime(g.date)}</small>`;
  }
  const h = teamById[g.home], a = teamById[g.away];
  return `<a class="game" href="#game/${g.code}">
    <span class="side ${homeCls}">${badge(h, "sm")}<span class="tname">${esc(h.name)}</span></span>
    <span class="score">${middle}</span>
    <span class="side away ${awayCls}"><span class="tname">${esc(a.name)}</span>${badge(a, "sm")}</span>
  </a>`;
}

const latestRound = () => played.length ? Math.max(...played.map(g => g.round)) : 0;
const nextRound = () => upcoming.length ? Math.min(...upcoming.map(g => g.round)) : null;
// leaders need a minimum number of games so one big night doesn't top the list
const minGames = () => Math.ceil(Math.max(0, ...players.map(p => p.gp)) / 2);

// ---------- Pages ----------
const pages = {
  home() {
    const lr = latestRound(), nr = nextRound();
    const top = computeStandings().slice(0, 10);
    return `
      <h1>EuroLeague ${esc(SEASON)}</h1>
      <div class="grid-2">
        <div>
          <div class="card">
            <h2>${L("Latest results", "Paskutiniai rezultatai")}${lr ? ` — ${L(`Round ${lr}`, `${lr} turas`)}` : ""}</h2>
            ${played.filter(g => g.round === lr).map(g => gameRow(g)).join("") || `<p class='muted'>${L("No games played yet.", "Rungtynių dar nebuvo.")}</p>`}
          </div>
          <div class="card">
            <h2>${L("Next games", "Artimiausios rungtynės")}${nr ? ` — ${L(`Round ${nr}`, `${nr} turas`)}` : ""}</h2>
            ${nr ? upcoming.filter(g => g.round === nr).map(g => gameRow(g, true)).join("") : `<p class='muted'>${L("Season finished.", "Sezonas baigėsi.")}</p>`}
            <p class="note">${L("Grey scores are predictions.", "Pilki rezultatai yra prognozės.")} <a href="#predictions">${L("See all predictions →", "Visos prognozės →")}</a></p>
          </div>
        </div>
        <div>
          <div class="card">
            <h2>${L("Standings", "Turnyrinė lentelė")}</h2>
            ${standingsTable(top, true)}
            <p class="note"><a href="#standings">${L("Full standings →", "Visa lentelė →")}</a></p>
          </div>
          <div class="card">
            <h2>${L("Leaders", "Lyderiai")}</h2>
            ${leaderList("pts", L("Points", "Taškai"))}${leaderList("reb", L("Rebounds", "Atkovoti kamuoliai"))}${leaderList("ast", L("Assists", "Rezultatyvūs perdavimai"))}${leaderList("pir", L("PIR", "Naudingumas (PIR)"))}
            <p class="note"><a href="#stats">${L("All player stats →", "Visa žaidėjų statistika →")}</a></p>
          </div>
        </div>
      </div>`;
  },

  standings() {
    return `<h1>${L("Standings", "Turnyrinė lentelė")}</h1><div class="card">${standingsTable(computeStandings())}</div>${seasonForecast()}`;
  },

  stats([view]) {
    const tabs = `<div class="tabs">
      <a href="#stats" class="${view === "teams" ? "" : "active"}">${L("Players", "Žaidėjai")}</a>
      <a href="#stats/teams" class="${view === "teams" ? "active" : ""}">${L("Teams", "Komandos")}</a></div>`;
    if (view === "teams") return `<h1>${L("Team statistics", "Komandų statistika")}</h1>${tabs}
      <div class="card" id="teamStatsTable"></div>
      <p class="note">${teamStatsNote()} ${L("Click a column header to sort.", "Paspauskite stulpelio pavadinimą, kad surikiuotumėte.")}</p>`;
    return `<h1>${L("Player statistics", "Žaidėjų statistika")}</h1>${tabs}
      <div class="controls">
        <label>${L("Team", "Komanda")}
          <select id="teamFilter">
            <option value="">${L("All teams", "Visos komandos")}</option>
            ${TEAMS.map(t => `<option value="${t.id}">${esc(t.name)}</option>`).join("")}
          </select>
        </label>
        <span class="note">${L("Per-game averages. Click a column header to sort.", "Vidurkiai per rungtynes. Paspauskite stulpelio pavadinimą, kad surikiuotumėte.")}</span>
      </div>
      <div class="card" id="statsTable"></div>
      <p class="note">${L(
        `2P% / 3P% / FT% = two-point, three-point and free-throw accuracy; TO = turnovers; +/− = the team's point
         difference while the player is on court. Grey percentages have too few attempts to be ranked (under 2
         two-pointers, 1.5 threes or 1.5 free throws a game).`,
        `2T% / 3T% / BM% = dvitaškių, tritaškių ir baudų metimų tikslumas; KL = klaidos; +/− = komandos taškų skirtumas,
         kol žaidėjas aikštėje. Pilki procentai turi per mažai metimų, kad būtų rikiuojami (mažiau nei 2 dvitaškiai,
         1,5 tritaškio ar 1,5 baudos metimo per rungtynes).`)}</p>`;
  },

  teams() {
    return `<h1>${L("Teams", "Komandos")}</h1>
      <div class="grid-teams">
        ${TEAMS.map(t => `
          <a class="team-card" href="#team/${t.id}">${badge(t)}
            <span><b>${esc(t.name)}</b><small>${esc(t.city)}, ${esc(t.country)}</small></span>
          </a>`).join("")}
      </div>`;
  },

  player([code]) {
    return playerPage(code);
  },

  team([id]) {
    const t = teamById[id];
    if (!t) return notFound();
    const st = computeStandings();
    const pos = st.findIndex(r => r.id === id);
    const r = st[pos];
    const games = GAMES.filter(g => g.home === id || g.away === id);
    return `
      <p><a href="#teams">${L("← All teams", "← Visos komandos")}</a></p>
      <h1 class="team-title">${badge(t, "lg")} ${esc(t.name)}</h1>
      <p class="muted">${t.fullName && t.fullName !== t.name ? `${esc(t.fullName)} · ` : ""}${esc(t.city)}, ${esc(t.country)}${t.coach ? ` · ${L("Coach", "Treneris")}: ${esc(t.coach)}` : ""}<br>
        ${L(`Position ${pos + 1}`, `${pos + 1} vieta`)} · ${r.w}–${r.l} · ${signed(r.diff)} ${L("point difference", "taškų skirtumas")}</p>
      ${teamStatsCard(id)}
      <div class="card">
        <h2>${L("Players", "Žaidėjai")}</h2>
        ${playerTable(t.players, false)}
      </div>
      <div class="card">
        <h2>${L("Games", "Rungtynės")}</h2>
        ${games.map(g => gameRow(g, true)).join("")}
      </div>`;
  },

  schedule() {
    const rounds = [...new Set(GAMES.map(g => g.round))].sort((a, b) => a - b);
    return `<h1>${L("Schedule & results", "Tvarkaraštis ir rezultatai")}</h1>
      <div class="controls">
        <button id="prevRound">${L("← Previous", "← Ankstesnis")}</button>
        <select id="roundSelect">${rounds.map(r => `<option value="${r}">${L(`Round ${r}`, `${r} turas`)}</option>`).join("")}</select>
        <button id="nextRound">${L("Next →", "Kitas →")}</button>
        <label>${L("Team", "Komanda")}
          <select id="schedTeam"><option value="">${L("All teams", "Visos komandos")}</option>
            ${TEAMS.map(t => `<option value="${t.id}">${esc(t.name)}</option>`).join("")}
          </select>
        </label>
      </div>
      <div class="card" id="roundGames"></div>`;
  },

  game([code]) {
    const g = gameByCode[code];
    if (!g) return notFound();
    const h = teamById[g.home], a = teamById[g.away];
    const middle = g.score
      ? `<div class="big">${g.score[0]} – ${g.score[1]}</div><div class="muted">${L("Final", "Baigta")}</div>`
      : `<div class="big muted">vs</div><div class="muted">${fmtTime(g.date)} ${L("local time", "vietos laiku")}</div>`;
    const earlier = played.filter(x => x !== g &&
      ((x.home === g.home && x.away === g.away) || (x.home === g.away && x.away === g.home)));
    let body;
    if (g.score) {
      const pr = g.pred;
      const hit = pr && (pr[2] >= 0.5) === (g.score[0] > g.score[1]);
      body = `
        ${pr ? `<div class="card">
          <h2>${L("Pre-game prediction", "Prognozė prieš rungtynes")} <span class="${hit ? "plus" : "minus"}">${hit ? L("✓ correct", "✓ pasitvirtino") : L("✗ wrong", "✗ nepasitvirtino")}</span></h2>
          ${probBar(g.home, g.away, pr[2])}
          <p>${L("Predicted", "Prognozė")}: <b>${esc(h.name)} ${pr[0]} – ${pr[1]} ${esc(a.name)}</b> · ${L("Final", "Rezultatas")}: ${g.score[0]} – ${g.score[1]}</p>
        </div>` : ""}
        ${quartersTable(g)}
        <div class="card"><h2>${esc(h.name)}</h2>${boxTable(g.box.home)}</div>
        <div class="card"><h2>${esc(a.name)}</h2>${boxTable(g.box.away)}</div>`;
    } else {
      const p = predict(g.home, g.away, g.neutral);
      body = `
        <div class="card">
          <h2>${L("Prediction", "Prognozė")}</h2>
          ${probBar(g.home, g.away, p.homeWin)}
          <p>${L("Predicted score", "Prognozuojamas rezultatas")}: <b>${esc(h.name)} ${p.homePts} – ${p.awayPts} ${esc(a.name)}</b></p>
          <p class="note">${L(`Based on both teams' ratings (this season's results, last season and summer roster changes)
            plus ${MODEL.hca} points home advantage.`, `Pagal abiejų komandų reitingus (šio sezono rezultatai, praėjęs sezonas ir vasaros
            sudėties pokyčiai) ir ${MODEL.hca} taškų namų aikštės pranašumą.`)} <a href="#predictions">${L("How it works", "Kaip tai veikia")}</a></p>
        </div>
        ${earlier.length ? `<div class="card"><h2>${L("Earlier meetings this season", "Ankstesnės šio sezono akistatos")}</h2>${earlier.map(x => gameRow(x)).join("")}</div>` : ""}
        <div class="grid-2">
          <div class="card"><h2>${esc(h.name)}</h2>${playerTable(h.players, false, true)}</div>
          <div class="card"><h2>${esc(a.name)}</h2>${playerTable(a.players, false, true)}</div>
        </div>`;
    }
    return `
      <p><a href="#schedule">${L("← Schedule", "← Tvarkaraštis")}</a></p>
      <div class="card">
        <p class="muted center" style="margin-top:0">${L(`Round ${g.round}`, `${g.round} turas`)} · ${fmtDate(g.date)}${g.venue ? ` · ${esc(g.venue)}` : ""}</p>
        <div class="scoreboard">
          <div><a href="#team/${h.id}">${badge(h, "xl")}</a><div><b>${esc(h.name)}</b></div><div class="muted">${L("Home", "Namuose")}</div></div>
          <div>${middle}</div>
          <div><a href="#team/${a.id}">${badge(a, "xl")}</a><div><b>${esc(a.name)}</b></div><div class="muted">${L("Away", "Svečiuose")}</div></div>
        </div>
      </div>
      ${body}`;
  },

  predictions() {
    const rounds = [...new Set(upcoming.map(g => g.round))].sort((a, b) => a - b).slice(0, 2);
    const rec = predictionRecord();
    const lr = latestRound(), lrRec = predictionRecord(played.filter(g => g.round === lr));
    return `<h1>${L("Predictions", "Prognozės")}</h1>
      ${rec.total ? `<div class="card">
        <h2>${L("Track record this season", "Šio sezono rezultatai")}</h2>
        <p class="record">${L(`<b>${rec.right} of ${rec.total}</b> winners picked correctly`, `Teisingai atspėta <b>${rec.right} iš ${rec.total}</b> nugalėtojų`)} (${Math.round(100 * rec.right / rec.total)}%)
          · ${L(`Round ${lr}`, `${lr} turas`)}: ${lrRec.right}/${lrRec.total}</p>
        <p class="note">${L(`Every played game was predicted using only the games before it. Over the last three
          seasons this model picked 67% of winners; early-season rounds are the hardest.`, `Kiekvienos sužaistos rungtynės prognozuotos
          naudojant tik ankstesnes rungtynes. Per tris praėjusius sezonus modelis atspėjo 67 % nugalėtojų; sezono pradžia sunkiausia.`)}</p>
      </div>` : ""}
      ${roundHistory()}
      <div class="card">
        <h2>${L("Pick any match-up", "Pasirinkite bet kurią porą")}</h2>
        <div class="controls">
          <label>${L("Home", "Namuose")} <select id="pHome">${TEAMS.map(t => `<option value="${t.id}">${esc(t.name)}</option>`).join("")}</select></label>
          <label>${L("Away", "Svečiuose")} <select id="pAway">${TEAMS.map((t, i) => `<option value="${t.id}" ${i === 1 ? "selected" : ""}>${esc(t.name)}</option>`).join("")}</select></label>
        </div>
        <div id="customPrediction"></div>
      </div>
      ${rounds.map((r, i) => `
        <div class="card">
          <h2>${L(`Round ${r}`, `${r} turas`)}${i === 0 ? L(" — next up", " — artimiausias") : ""}</h2>
          ${upcoming.filter(g => g.round === r).map(g => {
            const p = predict(g.home, g.away, g.neutral);
            const fav = p.homeWin >= 0.5 ? teamById[g.home] : teamById[g.away];
            return `${gameRow(g, true)}${probBar(g.home, g.away, p.homeWin)}
              <p class="note" style="margin-top:0">${L("Pick", "Spėjimas")}: <span class="pick">${esc(fav.name)}</span></p>`;
          }).join("")}
        </div>`).join("") || `<div class='card'><p class='muted'>${L("No upcoming games.", "Artimiausių rungtynių nėra.")}</p></div>`}
      <div class="card note">
        <h2>${L("How it works", "Kaip tai veikia")}</h2>
        ${L(`<p>Every team has an attack and a defence rating: how many points it scores and allows compared to an
          average EuroLeague team, adjusted for the strength of the opponents it played.</p>
        <p>Before the season, ratings start from last season's level, adjusted for summer transfers: players
          who arrived or left are valued by their EuroLeague production (PIR) last season. As games are played,
          this season's results take over, with recent games counting more.</p>
        <p>For a game, both teams' ratings give a predicted score, the home team gets +${MODEL.hca} points,
          and the margin is turned into a win chance. All settings were chosen by testing on the 2023–24,
          2024–25 and 2025–26 seasons. Later rounds are on the <a href="#schedule">schedule</a> page.</p>`,
        `<p>Kiekviena komanda turi puolimo ir gynybos reitingą: kiek taškų ji pelno ir praleidžia, palyginti su
          vidutine Eurolygos komanda, atsižvelgiant į varžovų stiprumą.</p>
        <p>Prieš sezoną reitingai prasideda nuo praėjusio sezono lygio, pakoreguoto pagal vasaros perėjimus:
          atvykę ir išvykę žaidėjai vertinami pagal jų praėjusio sezono Eurolygos naudingumą (PIR). Vykstant sezonui
          vis daugiau lemia šio sezono rezultatai, o naujesnės rungtynės svarbesnės.</p>
        <p>Rungtynėms abiejų komandų reitingai duoda prognozuojamą rezultatą, namų komanda gauna +${MODEL.hca} taškus,
          o skirtumas paverčiamas pergalės tikimybe. Visi nustatymai parinkti tikrinant 2023–24, 2024–25 ir 2025–26
          sezonuose. Vėlesni turai yra <a href="#schedule">tvarkaraštyje</a>.</p>`)}
      </div>`;
  },
};

const playerLink = (code, name) => (code ? `<a class="plain" href="#player/${esc(code)}">${esc(name)}</a>` : esc(name));

// every game a player was listed for: [{game, line, home?}], oldest first
function playerGames(code) {
  const out = [];
  played.forEach(g => {
    for (const side of ["home", "away"]) {
      const line = g.box && g.box[side].find(l => l[9] === code);
      if (line) out.push({ g, line, home: side === "home" });
    }
  });
  return out;
}

function playerPage(code) {
  const entries = players.filter(p => p.code === code); // more than one if he changed clubs this season
  if (!entries.length) return notFound();
  const p = entries.find(e => e.gp) || entries[0];
  const t = teamById[p.team];
  const log = playerGames(code);
  const fmtMin = m => `${Math.floor(m)}:${String(Math.round((m % 1) * 60)).padStart(2, "0")}`;
  const pctTile = (label, key, mi, ai) => `<div class="stat-tile"><small>${label}</small>
    <b>${p[key] == null ? "–" : p[key].toFixed(1)}</b><span class="muted">${p.sh[mi]}/${p.sh[ai]}</span></div>`;
  const tile = (label, key) => `<div class="stat-tile"><small>${label}</small>
    <b>${key === "pm" ? signed1(p.pm) : num(p[key], key)}</b><span class="muted">${rankOf(p, key)}</span></div>`;
  const best = log.filter(e => e.line[2]).sort((a, b) => b.line[8] - a.line[8])[0];
  return `
    <p><a href="#team/${t.id}">← ${esc(t.name)}</a></p>
    <h1 class="team-title">${badge(t, "lg")} ${esc(p.name)}</h1>
    <p class="muted">${p.num ? `#${esc(p.num)} · ` : ""}${esc(p.pos)}${p.pos ? " · " : ""}${esc(p.nat)} · ${teamLink(t.id, "sm").replace('class="team-cell"', 'class="team-cell inline"')}
      ${entries.length > 1 ? ` · ${L("also played for", "taip pat žaidė už")} ${entries.filter(e => e !== p).map(e => esc(teamById[e.team].name)).join(", ")}` : ""}</p>
    ${p.gp ? `<div class="card">
      <h2>${L("Season averages", "Sezono vidurkiai")} <span class="muted">· ${p.gp} ${L("games", "rungt.")}</span></h2>
      <div class="stat-tiles">
        ${tile("MIN", "min")}${tile(L("PTS", "TŠK"), "pts")}${tile(L("REB", "AK"), "reb")}${tile(L("AST", "RP"), "ast")}
        ${tile(L("STL", "PER"), "stl")}${tile(L("BLK", "BL"), "blk")}${tile(L("TO", "KL"), "tov")}${tile(L("PIR", "NAUD"), "pir")}${tile("+/−", "pm")}
        ${pctTile(L("2P%", "2T%"), "p2", 0, 1)}${pctTile(L("3P%", "3T%"), "p3", 2, 3)}${pctTile(L("FT%", "BM%"), "ft", 4, 5)}
      </div>
      <p class="note">${L(
        `Under each number: rank among the ${rankPool().length} players with at least ${minGames()} games (for shooting: makes/attempts).`,
        `Po kiekvienu skaičiumi: vieta tarp ${rankPool().length} žaidėjų, sužaidusių bent ${minGames()} rungt. (metimams: pataikyta/mesta).`)}
        ${best ? L(`Best game by PIR: <a href="#game/${best.g.code}">${best.line[8]} against ${esc(teamById[best.home ? best.g.away : best.g.home].name)}</a>.`,
                   `Geriausios rungtynės pagal naudingumą: <a href="#game/${best.g.code}">${best.line[8]} prieš ${esc(teamById[best.home ? best.g.away : best.g.home].name)}</a>.`) : ""}</p>
    </div>` : `<div class="card"><p class="muted">${L("Has not played this season.", "Šį sezoną dar nežaidė.")}</p></div>`}
    ${log.length ? `<div class="card">
      <h2>${L("Game log", "Rungtynės")}</h2>
      <div class="table-wrap"><table>
        <thead><tr><th class="left">${L("Date", "Data")}</th><th class="left">${L("Opponent", "Varžovas")}</th><th>${L("Result", "Rezultatas")}</th>
          ${STAT_COLS().slice(1).map(([, l]) => `<th>${l}</th>`).join("")}</tr></thead>
        <tbody>${[...log].reverse().map(({ g, line, home }) => {
          const us = home ? g.score[0] : g.score[1], them = home ? g.score[1] : g.score[0];
          return `<tr class="${line[2] ? "" : "dnp"}">
            <td class="left"><a class="plain" href="#game/${g.code}">${fmtDate(g.date)}</a></td>
            <td class="left"><span class="muted">${home ? L("vs", "prieš") : "@"}</span> ${esc(teamById[home ? g.away : g.home].name)}</td>
            <td><span class="${us > them ? "plus" : "minus"}">${us > them ? L("W", "P") : L("L", "Pr")}</span> ${us}–${them}</td>
            ${line[2] ? `<td>${fmtMin(line[2])}</td>${line.slice(3, 9).map(v => `<td>${v}</td>`).join("")}`
                      : `<td>DNP</td>${"<td></td>".repeat(6)}`}
          </tr>`;
        }).join("")}</tbody>
      </table></div>
    </div>` : ""}`;
}

// players with enough games to be ranked, and a player's rank in one stat ("" if he isn't in that pool)
const rankPool = () => players.filter(q => q.gp && q.gp >= minGames());
function rankOf(p, key) {
  const pool = rankPool();
  if (!pool.includes(p)) return "";
  const lowerBetter = key === "tov";
  const rank = 1 + pool.filter(q => (lowerBetter ? q[key] < p[key] : q[key] > p[key])).length;
  return L(`#${rank}`, `${rank} vieta`);
}

function notFound() {
  return `<h1>${L("Not found", "Puslapis nerastas")}</h1><p><a href="#home">${L("Back to home", "Į pradžią")}</a></p>`;
}

// ---------- Tables ----------
const STAT_COLS = () => [
  ["gp", L("GP", "R")], ["min", "MIN"], ["pts", L("PTS", "TŠK")], ["reb", L("REB", "AK")], ["ast", L("AST", "RP")],
  ["stl", L("STL", "PER")], ["blk", L("BLK", "BL")], ["pir", L("PIR", "NAUD")],
];
// only in the full player tables (box scores keep the columns above)
const EXTRA_COLS = () => [
  ["p2", L("2P%", "2T%")], ["p3", L("3P%", "3T%")], ["ft", L("FT%", "BM%")], ["tov", L("TO", "KL")], ["pm", "+/−"],
];
// A shooting percentage only counts for ranking with enough attempts per game: [index of attempts in p.sh, minimum]
const MIN_ATTEMPTS = { p2: [1, 2], p3: [3, 1.5], ft: [5, 1.5] };
const qualifies = (p, key) => !MIN_ATTEMPTS[key] || (p.sh && p.sh[MIN_ATTEMPTS[key][0]] >= MIN_ATTEMPTS[key][1] * p.gp);
// value used for sorting: players without enough attempts go to the bottom of a percentage column
const sortValue = (p, key) => (p[key] == null || !qualifies(p, key) ? -Infinity : p[key]);
const statCell = (p, key) => {
  if (!p.gp && key !== "gp") return "–";
  if (p[key] == null) return "–";
  if (key === "pm") return signed1(p.pm);
  return MIN_ATTEMPTS[key] && !qualifies(p, key) ? `<span class="muted">${num(p[key], key)}</span>` : num(p[key], key);
};

// ---------- Team statistics ----------
// [key, label, lower is better]
const TEAM_COLS = () => [
  ["pts", L("PTS", "TŠK")], ["opp", L("OPP", "PRAL"), true], ["ortg", L("OFF", "PUOL")], ["drtg", L("DEF", "GYN"), true],
  ["net", L("NET", "SKIRT")], ["pace", L("PACE", "TEMPAS")], ["efg", "eFG%"], ["oefg", L("OPP eFG%", "VARŽ eFG%"), true],
  ["p2", L("2P%", "2T%")], ["p3", L("3P%", "3T%")], ["ft", L("FT%", "BM%")], ["reb", L("REB", "AK")],
  ["orebp", L("OREB%", "PUOL AK%")], ["ast", L("AST", "RP")], ["tov", L("TO", "KL"), true],
  ["stl", L("STL", "PER")], ["blk", L("BLK", "BL")],
];
const teamStats = () => (typeof TEAM_STATS !== "undefined" ? TEAM_STATS : {});
// 1 = best in the league for that column
function teamRank(id, key, lowerBetter) {
  const ts = teamStats(), mine = ts[id][key];
  return 1 + Object.values(ts).filter(t => (lowerBetter ? t[key] < mine : t[key] > mine)).length;
}

function teamStatsTable(sortKey) {
  const ts = teamStats(), cols = TEAM_COLS();
  const lower = (cols.find(c => c[0] === sortKey) || [])[2];
  const ids = Object.keys(ts).sort((a, b) => (lower ? ts[a][sortKey] - ts[b][sortKey] : ts[b][sortKey] - ts[a][sortKey]));
  return `<div class="table-wrap"><table>
    <thead><tr><th>#</th><th class="left">${L("Team", "Komanda")}</th>
      ${cols.map(([k, label]) => `<th class="sortable ${k === sortKey ? "sorted" : ""}" data-sort="${k}">${label}</th>`).join("")}
    </tr></thead>
    <tbody>${ids.map((id, i) => `<tr><td class="pos">${i + 1}</td><td class="left">${teamLink(id)}</td>
      ${cols.map(([k]) => `<td>${k === "net" ? signed1(ts[id][k]) : ts[id][k].toFixed(1)}</td>`).join("")}</tr>`).join("")}
    </tbody></table></div>`;
}

const teamStatsNote = () => L(
  `Per game. OFF / DEF = points scored / allowed per 100 possessions, NET = their difference, PACE = possessions per game,
   eFG% = shooting percentage counting a three as 1.5 makes, OREB% = share of own misses rebounded.`,
  `Per rungtynes. PUOL / GYN = pelnyti / praleisti taškai per 100 atakų, SKIRT = jų skirtumas, TEMPAS = atakos per rungtynes,
   eFG% = metimų tikslumas, kai tritaškis skaičiuojamas kaip 1,5 pataikymo, PUOL AK% = atkovota savo netaiklių metimų dalis.`);

// the main numbers of one team with its league rank, for the team page
function teamStatsCard(id) {
  const ts = teamStats();
  if (!ts[id]) return "";
  const keys = ["pts", "opp", "ortg", "drtg", "net", "pace", "efg", "p3", "reb", "ast", "tov"];
  const cols = TEAM_COLS().filter(c => keys.includes(c[0]));
  return `<div class="card">
    <h2>${L("Team statistics", "Komandos statistika")}</h2>
    <div class="stat-tiles">${cols.map(([k, label, lower]) => `<div class="stat-tile">
      <small>${label}</small><b>${k === "net" ? signed1(ts[id][k]) : ts[id][k].toFixed(1)}</b>
      <span class="muted">${L(`#${teamRank(id, k, lower)}`, `${teamRank(id, k, lower)} vieta`)}</span></div>`).join("")}
    </div>
    <p class="note">${teamStatsNote()} <a href="#stats/teams">${L("All teams →", "Visos komandos →")}</a></p>
  </div>`;
}

function playerTable(list, showTeam, compact = false, sortKey = null) {
  const cols = compact ? STAT_COLS().filter(([k]) => ["gp", "pts", "reb", "ast", "pir"].includes(k)) : [...STAT_COLS(), ...EXTRA_COLS()];
  return `<div class="table-wrap"><table>
    <thead><tr>
      ${showTeam ? "" : "<th>#</th>"}<th class="left">${L("Player", "Žaidėjas")}</th>${compact ? "" : `<th class='left'>${L("Pos", "Poz.")}</th>`}
      ${showTeam ? `<th class="left">${L("Team", "Komanda")}</th>` : ""}
      ${cols.map(([k, label]) => `<th class="${sortKey !== null ? "sortable" : ""} ${k === sortKey ? "sorted" : ""}" data-sort="${k}">${label}</th>`).join("")}
    </tr></thead>
    <tbody>
      ${list.map(p => `<tr>
        ${showTeam ? "" : `<td class="muted">${esc(p.num)}</td>`}
        <td class="left">${playerLink(p.code, p.name)} <span class="muted">${esc(p.nat)}</span></td>
        ${compact ? "" : `<td class="left muted">${esc(p.pos)}</td>`}
        ${showTeam ? `<td class="left">${teamLink(p.team)}</td>` : ""}
        ${cols.map(([k]) => `<td>${statCell(p, k)}</td>`).join("")}
      </tr>`).join("")}
    </tbody>
  </table></div>`;
}

// box score line: [name, number, min, pts, reb, ast, stl, blk, pir]
function boxTable(lines) {
  const fmtMin = m => m ? `${Math.floor(m)}:${String(Math.round((m % 1) * 60)).padStart(2, "0")}` : "DNP";
  const sorted = [...lines].sort((a, b) => b[2] - a[2]);
  return `<div class="table-wrap"><table>
    <thead><tr><th>#</th><th class="left">${L("Player", "Žaidėjas")}</th>${STAT_COLS().slice(1).map(([, l]) => `<th>${l}</th>`).join("")}</tr></thead>
    <tbody>${sorted.map(l => `<tr class="${l[2] ? "" : "dnp"}">
      <td class="muted">${esc(l[1])}</td><td class="left">${playerLink(l[9], l[0])}</td><td>${fmtMin(l[2])}</td>
      ${l.slice(3, 9).map(v => `<td>${l[2] ? v : ""}</td>`).join("")}
    </tr>`).join("")}</tbody>
  </table></div>`;
}

function quartersTable(g) {
  const periods = g.quarters[0].length;
  const label = i => i < 4 ? `Q${i + 1}` : `OT${periods > 5 ? i - 3 : ""}`;
  return `<div class="card"><div class="table-wrap"><table>
    <thead><tr><th class="left">${L("Team", "Komanda")}</th>${g.quarters[0].map((_, i) => `<th>${label(i)}</th>`).join("")}<th>${L("Total", "Iš viso")}</th></tr></thead>
    <tbody>${[g.home, g.away].map((id, s) => `<tr>
      <td class="left">${teamLink(id)}</td>${g.quarters[s].map(q => `<td>${q}</td>`).join("")}<td><b>${g.score[s]}</b></td>
    </tr>`).join("")}</tbody>
  </table></div></div>`;
}

function leaderList(key, label) {
  const min = minGames();
  const top = players.filter(p => p.gp && p.gp >= min).sort((a, b) => b[key] - a[key]).slice(0, 3);
  return `<div style="margin-bottom:10px"><div class="round-title">${label}</div>
    ${top.map((p, i) => `<div class="leader">
      <span>${i + 1}. ${playerLink(p.code, p.name)} <span class="muted">${esc(teamById[p.team].short)}</span></span><b>${num(p[key])}</b></div>`).join("")
      || `<span class='muted'>${L("No games yet.", "Rungtynių dar nebuvo.")}</span>`}
  </div>`;
}

// ---------- Interactivity per page ----------
const setup = {
  stats([view]) {
    if (view === "teams") {
      let key = "net";
      const tbox = document.getElementById("teamStatsTable");
      const draw = () => {
        tbox.innerHTML = Object.keys(teamStats()).length ? teamStatsTable(key)
          : `<p class='muted'>${L("No games played yet.", "Rungtynių dar nebuvo.")}</p>`;
        tbox.querySelectorAll("th.sortable").forEach(th =>
          th.addEventListener("click", () => { key = th.dataset.sort; draw(); }));
      };
      draw();
      return;
    }
    let sortKey = "pts";
    const sel = document.getElementById("teamFilter");
    const box = document.getElementById("statsTable");
    const render = () => {
      const list = players.filter(p => p.gp && (!sel.value || p.team === sel.value))
        .sort((a, b) => sortValue(b, sortKey) - sortValue(a, sortKey) || b.pts - a.pts);
      box.innerHTML = list.length ? playerTable(list, true, false, sortKey) : `<p class='muted'>${L("No games played yet.", "Rungtynių dar nebuvo.")}</p>`;
      box.querySelectorAll("th.sortable").forEach(th =>
        th.addEventListener("click", () => { sortKey = th.dataset.sort; render(); }));
    };
    sel.addEventListener("change", render);
    render();
  },

  schedule() {
    const sel = document.getElementById("roundSelect");
    const teamSel = document.getElementById("schedTeam");
    const box = document.getElementById("roundGames");
    const prev = document.getElementById("prevRound");
    const next = document.getElementById("nextRound");
    sel.value = nextRound() ?? latestRound();
    const render = () => {
      const r = Number(sel.value);
      const games = GAMES.filter(g => g.round === r && (!teamSel.value || g.home === teamSel.value || g.away === teamSel.value));
      box.innerHTML = `<h2>${L(`Round ${r}`, `${r} turas`)}</h2>` + (games.map(g => gameRow(g, true)).join("") || `<p class='muted'>${L("No games.", "Rungtynių nėra.")}</p>`)
        + (games.some(g => !g.score) ? `<p class='note'>${L("Grey scores are predictions.", "Pilki rezultatai yra prognozės.")}</p>` : "");
      prev.disabled = sel.selectedIndex === 0;
      next.disabled = sel.selectedIndex === sel.options.length - 1;
    };
    prev.addEventListener("click", () => { sel.selectedIndex--; render(); });
    next.addEventListener("click", () => { sel.selectedIndex++; render(); });
    sel.addEventListener("change", render);
    teamSel.addEventListener("change", render);
    render();
  },

  predictions() {
    const h = document.getElementById("pHome"), a = document.getElementById("pAway");
    const box = document.getElementById("customPrediction");
    const render = () => {
      if (h.value === a.value) { box.innerHTML = `<p class='muted'>${L("Choose two different teams.", "Pasirinkite dvi skirtingas komandas.")}</p>`; return; }
      const p = predict(h.value, a.value);
      box.innerHTML = `${probBar(h.value, a.value, p.homeWin)}
        <p>${L("Predicted score", "Prognozuojamas rezultatas")}: <b>${esc(teamById[h.value].name)} ${p.homePts} – ${p.awayPts} ${esc(teamById[a.value].name)}</b></p>`;
    };
    h.addEventListener("change", render);
    a.addEventListener("change", render);
    render();
  },
};

// ---------- Router ----------
function route() {
  const [page, ...params] = (location.hash.slice(1) || "home").split("/");
  const view = pages[page];
  $app.innerHTML = view ? view(params) : notFound();
  if (view && setup[page]) setup[page](params);
  const navKey = { team: "teams", player: "teams", game: "schedule" }[page] || page;
  document.querySelectorAll("nav a").forEach(a => a.classList.toggle("active", a.dataset.nav === navKey));
  window.scrollTo(0, 0);
}

document.querySelectorAll("[data-lang]").forEach(b => b.addEventListener("click", () => setLanguage(b.dataset.lang)));
applyLanguage();
window.addEventListener("hashchange", route);
document.addEventListener("DOMContentLoaded", route); // after js/betting.js has added its page
