// =====================================================================
//  Euroleague Hub — simple single-page app (no build step, no libraries)
//  Data comes from js/data.js, generated by update_data.py.
//  Pages are selected by the URL hash: #home, #standings, #stats,
//  #teams, #team/MAD, #schedule, #game/27, #predictions, #bets (js/betting.js)
// =====================================================================


// ---------- Prepare data ----------
const teamById = {};
const players = [];
TEAMS.forEach(team => {
  teamById[team.id] = team;
  team.players.forEach(p => { p.team = team.id; players.push(p); });
});
const gameByCode = {};
GAMES.forEach(g => { gameByCode[g.code] = g; });

const played = GAMES.filter(g => g.score);
const upcoming = GAMES.filter(g => !g.score);

// ---------- Helpers ----------
const $app = document.getElementById("app");
const esc = s => String(s ?? "").replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const fmtDate = d => new Date(d.slice(0, 10) + "T12:00:00").toLocaleDateString("en-GB", { weekday: "short", day: "numeric", month: "short" });
const fmtTime = d => d.slice(11, 16);
const signed = n => (n > 0 ? "+" : "") + n;
const num = (n, key) => key === "gp" ? n : Number(n).toFixed(1);

function badge(team, size = "") {
  return team.crest
    ? `<img class="crest ${size}" src="${esc(team.crest)}" alt="${esc(team.short)}" loading="lazy">`
    : `<span class="badge ${size}">${esc(team.short)}</span>`;
}
function teamLink(id, size = "sm") {
  const t = teamById[id];
  return `<a class="team-cell" href="#team/${t.id}">${badge(t, size)}<span>${esc(t.name)}</span></a>`;
}

// ---------- Standings ----------
function computeStandings() {
  const rows = {};
  TEAMS.forEach(t => rows[t.id] = { id: t.id, gp: 0, w: 0, l: 0, pf: 0, pa: 0, form: [] });

  played.forEach(g => {
    const [hs, as] = g.score;
    const h = rows[g.home], a = rows[g.away];
    h.gp++; a.gp++;
    h.pf += hs; h.pa += as;
    a.pf += as; a.pa += hs;
    if (hs > as) { h.w++; a.l++; h.form.push("W"); a.form.push("L"); }
    else { a.w++; h.l++; a.form.push("W"); h.form.push("L"); }
  });

  return Object.values(rows)
    .map(r => ({ ...r, diff: r.pf - r.pa, form: r.form.slice(-5) }))
    .sort((a, b) => b.w - a.w || b.diff - a.diff || b.pf - a.pf);
}

function standingsTable(rows, compact = false) {
  return `
    <div class="table-wrap"><table>
      <thead><tr>
        <th>#</th><th class="left">Team</th><th>GP</th><th>W</th><th>L</th>
        ${compact ? "" : "<th>PF</th><th>PA</th>"}<th>+/-</th>${compact ? "" : "<th>Form</th>"}
      </tr></thead>
      <tbody>
        ${rows.map((r, i) => `
          <tr class="${i < 6 ? "playoff" : i < 10 ? "playin" : ""}">
            <td class="pos">${i + 1}</td>
            <td class="left">${teamLink(r.id)}</td>
            <td>${r.gp}</td><td>${r.w}</td><td>${r.l}</td>
            ${compact ? "" : `<td>${r.pf}</td><td>${r.pa}</td>`}
            <td class="${r.diff > 0 ? "plus" : r.diff < 0 ? "minus" : ""}">${signed(r.diff)}</td>
            ${compact ? "" : `<td><span class="form">${r.form.map(f => `<b class="${f}">${f}</b>`).join("")}</span></td>`}
          </tr>`).join("")}
      </tbody>
    </table></div>
    <div class="legend"><span class="l-po">Playoffs (1–6)</span><span class="l-pi">Play-In (7–10)</span></div>`;
}

// ---------- Predictions ----------
// Team ratings come from model.py (via update_data.py) — see the README for how they're made.
function predict(homeId, awayId, neutral = false) {
  const t = MODEL.teams, h = neutral ? 0 : MODEL.hca / 2;
  const homePts = MODEL.avg + h + t[homeId][0] + t[awayId][1];
  const awayPts = MODEL.avg - h + t[awayId][0] + t[homeId][1];
  const margin = homePts - awayPts;
  const homeWin = 1 / (1 + Math.exp(-margin / MODEL.scale));
  let hp = Math.round(homePts), ap = Math.round(awayPts);
  if (hp === ap) margin >= 0 ? hp++ : ap++; // basketball has no draws
  return { homePts: hp, awayPts: ap, homeWin, margin, total: homePts + awayPts };
}

// how the model did on games already played (each predicted before tip-off)
function predictionRecord(games = played) {
  const done = games.filter(g => g.pred);
  const right = done.filter(g => (g.pred[2] >= 0.5) === (g.score[0] > g.score[1])).length;
  return { right, total: done.length };
}

function probBar(homeId, awayId, p) {
  const h = teamById[homeId], a = teamById[awayId];
  const hp = Math.round(p * 100), ap = 100 - hp;
  return `<div class="prob-bar">
    <div class="ph" style="width:${hp}%">${esc(h.short)} ${hp}%</div>
    <div class="pa" style="width:${ap}%">${ap}% ${esc(a.short)}</div>
  </div>`;
}

// ---------- Game rows ----------
function gameRow(g, showPrediction = false) {
  let middle, homeCls = "", awayCls = "";
  if (g.score) {
    const [hs, as] = g.score;
    homeCls = hs > as ? "winner" : "loser";
    awayCls = as > hs ? "winner" : "loser";
    middle = `${hs} – ${as}<small>Final · ${fmtDate(g.date)}</small>`;
  } else if (showPrediction) {
    const p = predict(g.home, g.away, g.neutral);
    middle = `<span class="muted">${p.homePts} – ${p.awayPts}</span><small>${fmtDate(g.date)} · ${fmtTime(g.date)}</small>`;
  } else {
    middle = `vs<small>${fmtDate(g.date)} · ${fmtTime(g.date)}</small>`;
  }
  const h = teamById[g.home], a = teamById[g.away];
  return `<a class="game" href="#game/${g.code}">
    <span class="side ${homeCls}">${badge(h, "sm")}<span class="tname">${esc(h.name)}</span></span>
    <span class="score">${middle}</span>
    <span class="side away ${awayCls}"><span class="tname">${esc(a.name)}</span>${badge(a, "sm")}</span>
  </a>`;
}

const latestRound = () => played.length ? Math.max(...played.map(g => g.round)) : 0;
const nextRound = () => upcoming.length ? Math.min(...upcoming.map(g => g.round)) : null;
// leaders need a minimum number of games so one big night doesn't top the list
const minGames = () => Math.ceil(Math.max(0, ...players.map(p => p.gp)) / 2);

// ---------- Pages ----------
const pages = {
  home() {
    const lr = latestRound(), nr = nextRound();
    const top = computeStandings().slice(0, 10);
    return `
      <h1>EuroLeague ${esc(SEASON)}</h1>
      <div class="grid-2">
        <div>
          <div class="card">
            <h2>Latest results${lr ? ` — Round ${lr}` : ""}</h2>
            ${played.filter(g => g.round === lr).map(g => gameRow(g)).join("") || "<p class='muted'>No games played yet.</p>"}
          </div>
          <div class="card">
            <h2>Next games${nr ? ` — Round ${nr}` : ""}</h2>
            ${nr ? upcoming.filter(g => g.round === nr).map(g => gameRow(g, true)).join("") : "<p class='muted'>Season finished.</p>"}
            <p class="note">Grey scores are predictions. <a href="#predictions">See all predictions →</a></p>
          </div>
        </div>
        <div>
          <div class="card">
            <h2>Standings</h2>
            ${standingsTable(top, true)}
            <p class="note"><a href="#standings">Full standings →</a></p>
          </div>
          <div class="card">
            <h2>Leaders</h2>
            ${leaderList("pts", "Points")}${leaderList("reb", "Rebounds")}${leaderList("ast", "Assists")}${leaderList("pir", "PIR")}
            <p class="note"><a href="#stats">All player stats →</a></p>
          </div>
        </div>
      </div>`;
  },

  standings() {
    return `<h1>Standings</h1><div class="card">${standingsTable(computeStandings())}</div>`;
  },

  stats() {
    return `<h1>Player statistics</h1>
      <div class="controls">
        <label>Team
          <select id="teamFilter">
            <option value="">All teams</option>
            ${TEAMS.map(t => `<option value="${t.id}">${esc(t.name)}</option>`).join("")}
          </select>
        </label>
        <span class="note">Per-game averages. Click a column header to sort.</span>
      </div>
      <div class="card" id="statsTable"></div>`;
  },

  teams() {
    return `<h1>Teams</h1>
      <div class="grid-teams">
        ${TEAMS.map(t => `
          <a class="team-card" href="#team/${t.id}">${badge(t)}
            <span><b>${esc(t.name)}</b><small>${esc(t.city)}, ${esc(t.country)}</small></span>
          </a>`).join("")}
      </div>`;
  },

  team([id]) {
    const t = teamById[id];
    if (!t) return notFound();
    const st = computeStandings();
    const pos = st.findIndex(r => r.id === id);
    const r = st[pos];
    const games = GAMES.filter(g => g.home === id || g.away === id);
    return `
      <p><a href="#teams">← All teams</a></p>
      <h1 class="team-title">${badge(t, "lg")} ${esc(t.name)}</h1>
      <p class="muted">${t.fullName && t.fullName !== t.name ? `${esc(t.fullName)} · ` : ""}${esc(t.city)}, ${esc(t.country)}${t.coach ? ` · Coach: ${esc(t.coach)}` : ""}<br>
        Position ${pos + 1} · ${r.w}–${r.l} · ${signed(r.diff)} point difference</p>
      <div class="card">
        <h2>Players</h2>
        ${playerTable(t.players, false)}
      </div>
      <div class="card">
        <h2>Games</h2>
        ${games.map(g => gameRow(g, true)).join("")}
      </div>`;
  },

  schedule() {
    const rounds = [...new Set(GAMES.map(g => g.round))].sort((a, b) => a - b);
    return `<h1>Schedule & results</h1>
      <div class="controls">
        <button id="prevRound">← Previous</button>
        <select id="roundSelect">${rounds.map(r => `<option value="${r}">Round ${r}</option>`).join("")}</select>
        <button id="nextRound">Next →</button>
        <label>Team
          <select id="schedTeam"><option value="">All teams</option>
            ${TEAMS.map(t => `<option value="${t.id}">${esc(t.name)}</option>`).join("")}
          </select>
        </label>
      </div>
      <div class="card" id="roundGames"></div>`;
  },

  game([code]) {
    const g = gameByCode[code];
    if (!g) return notFound();
    const h = teamById[g.home], a = teamById[g.away];
    const middle = g.score
      ? `<div class="big">${g.score[0]} – ${g.score[1]}</div><div class="muted">Final</div>`
      : `<div class="big muted">vs</div><div class="muted">${fmtTime(g.date)} local time</div>`;
    const earlier = played.filter(x => x !== g &&
      ((x.home === g.home && x.away === g.away) || (x.home === g.away && x.away === g.home)));
    let body;
    if (g.score) {
      const pr = g.pred;
      const hit = pr && (pr[2] >= 0.5) === (g.score[0] > g.score[1]);
      body = `
        ${pr ? `<div class="card">
          <h2>Pre-game prediction <span class="${hit ? "plus" : "minus"}">${hit ? "✓ correct" : "✗ wrong"}</span></h2>
          ${probBar(g.home, g.away, pr[2])}
          <p>Predicted: <b>${esc(h.name)} ${pr[0]} – ${pr[1]} ${esc(a.name)}</b> · Final: ${g.score[0]} – ${g.score[1]}</p>
        </div>` : ""}
        ${quartersTable(g)}
        <div class="card"><h2>${esc(h.name)}</h2>${boxTable(g.box.home)}</div>
        <div class="card"><h2>${esc(a.name)}</h2>${boxTable(g.box.away)}</div>`;
    } else {
      const p = predict(g.home, g.away, g.neutral);
      body = `
        <div class="card">
          <h2>Prediction</h2>
          ${probBar(g.home, g.away, p.homeWin)}
          <p>Predicted score: <b>${esc(h.name)} ${p.homePts} – ${p.awayPts} ${esc(a.name)}</b></p>
          <p class="note">Based on both teams' ratings (this season's results, last season and summer roster changes)
            plus ${MODEL.hca} points home advantage. <a href="#predictions">How it works</a></p>
        </div>
        ${earlier.length ? `<div class="card"><h2>Earlier meetings this season</h2>${earlier.map(x => gameRow(x)).join("")}</div>` : ""}
        <div class="grid-2">
          <div class="card"><h2>${esc(h.name)}</h2>${playerTable(h.players, false, true)}</div>
          <div class="card"><h2>${esc(a.name)}</h2>${playerTable(a.players, false, true)}</div>
        </div>`;
    }
    return `
      <p><a href="#schedule">← Schedule</a></p>
      <div class="card">
        <p class="muted center" style="margin-top:0">Round ${g.round} · ${fmtDate(g.date)}${g.venue ? ` · ${esc(g.venue)}` : ""}</p>
        <div class="scoreboard">
          <div><a href="#team/${h.id}">${badge(h, "xl")}</a><div><b>${esc(h.name)}</b></div><div class="muted">Home</div></div>
          <div>${middle}</div>
          <div><a href="#team/${a.id}">${badge(a, "xl")}</a><div><b>${esc(a.name)}</b></div><div class="muted">Away</div></div>
        </div>
      </div>
      ${body}`;
  },

  predictions() {
    const rounds = [...new Set(upcoming.map(g => g.round))].sort((a, b) => a - b).slice(0, 2);
    const rec = predictionRecord();
    const lr = latestRound(), lrRec = predictionRecord(played.filter(g => g.round === lr));
    return `<h1>Predictions</h1>
      ${rec.total ? `<div class="card">
        <h2>Track record this season</h2>
        <p class="record"><b>${rec.right} of ${rec.total}</b> winners picked correctly (${Math.round(100 * rec.right / rec.total)}%)
          · Round ${lr}: ${lrRec.right}/${lrRec.total}</p>
        <p class="note">Every played game was predicted using only the games before it. Over the last three
          seasons this model picked 67% of winners; early-season rounds are the hardest.</p>
      </div>` : ""}
      <div class="card">
        <h2>Pick any match-up</h2>
        <div class="controls">
          <label>Home <select id="pHome">${TEAMS.map(t => `<option value="${t.id}">${esc(t.name)}</option>`).join("")}</select></label>
          <label>Away <select id="pAway">${TEAMS.map((t, i) => `<option value="${t.id}" ${i === 1 ? "selected" : ""}>${esc(t.name)}</option>`).join("")}</select></label>
        </div>
        <div id="customPrediction"></div>
      </div>
      ${rounds.map((r, i) => `
        <div class="card">
          <h2>Round ${r}${i === 0 ? " — next up" : ""}</h2>
          ${upcoming.filter(g => g.round === r).map(g => {
            const p = predict(g.home, g.away, g.neutral);
            const fav = p.homeWin >= 0.5 ? teamById[g.home] : teamById[g.away];
            return `${gameRow(g, true)}${probBar(g.home, g.away, p.homeWin)}
              <p class="note" style="margin-top:0">Pick: <span class="pick">${esc(fav.name)}</span></p>`;
          }).join("")}
        </div>`).join("") || "<div class='card'><p class='muted'>No upcoming games.</p></div>"}
      <div class="card note">
        <h2>How it works</h2>
        <p>Every team has an attack and a defence rating: how many points it scores and allows compared to an
          average EuroLeague team, adjusted for the strength of the opponents it played.</p>
        <p>Before the season, ratings start from last season's level, adjusted for summer transfers: players
          who arrived or left are valued by their EuroLeague production (PIR) last season. As games are played,
          this season's results take over, with recent games counting more.</p>
        <p>For a game, both teams' ratings give a predicted score, the home team gets +${MODEL.hca} points,
          and the margin is turned into a win chance. All settings were chosen by testing on the 2023–24,
          2024–25 and 2025–26 seasons. Later rounds are on the <a href="#schedule">schedule</a> page.</p>
      </div>`;
  },
};

function notFound() {
  return `<h1>Not found</h1><p><a href="#home">Back to home</a></p>`;
}

// ---------- Tables ----------
const STAT_COLS = [
  ["gp", "GP"], ["min", "MIN"], ["pts", "PTS"], ["reb", "REB"], ["ast", "AST"],
  ["stl", "STL"], ["blk", "BLK"], ["pir", "PIR"],
];

function playerTable(list, showTeam, compact = false, sortKey = null) {
  const cols = compact ? STAT_COLS.filter(([k]) => ["gp", "pts", "reb", "ast", "pir"].includes(k)) : STAT_COLS;
  return `<div class="table-wrap"><table>
    <thead><tr>
      ${showTeam ? "" : "<th>#</th>"}<th class="left">Player</th>${compact ? "" : "<th class='left'>Pos</th>"}
      ${showTeam ? '<th class="left">Team</th>' : ""}
      ${cols.map(([k, label]) => `<th class="${sortKey !== null ? "sortable" : ""} ${k === sortKey ? "sorted" : ""}" data-sort="${k}">${label}</th>`).join("")}
    </tr></thead>
    <tbody>
      ${list.map(p => `<tr>
        ${showTeam ? "" : `<td class="muted">${esc(p.num)}</td>`}
        <td class="left">${esc(p.name)} <span class="muted">${esc(p.nat)}</span></td>
        ${compact ? "" : `<td class="left muted">${esc(p.pos)}</td>`}
        ${showTeam ? `<td class="left">${teamLink(p.team)}</td>` : ""}
        ${cols.map(([k]) => `<td>${p.gp || k === "gp" ? num(p[k], k) : "–"}</td>`).join("")}
      </tr>`).join("")}
    </tbody>
  </table></div>`;
}

// box score line: [name, number, min, pts, reb, ast, stl, blk, pir]
function boxTable(lines) {
  const fmtMin = m => m ? `${Math.floor(m)}:${String(Math.round((m % 1) * 60)).padStart(2, "0")}` : "DNP";
  const sorted = [...lines].sort((a, b) => b[2] - a[2]);
  return `<div class="table-wrap"><table>
    <thead><tr><th>#</th><th class="left">Player</th><th>MIN</th><th>PTS</th><th>REB</th><th>AST</th><th>STL</th><th>BLK</th><th>PIR</th></tr></thead>
    <tbody>${sorted.map(l => `<tr class="${l[2] ? "" : "dnp"}">
      <td class="muted">${esc(l[1])}</td><td class="left">${esc(l[0])}</td><td>${fmtMin(l[2])}</td>
      ${l.slice(3).map(v => `<td>${l[2] ? v : ""}</td>`).join("")}
    </tr>`).join("")}</tbody>
  </table></div>`;
}

function quartersTable(g) {
  const periods = g.quarters[0].length;
  const label = i => i < 4 ? `Q${i + 1}` : `OT${periods > 5 ? i - 3 : ""}`;
  return `<div class="card"><div class="table-wrap"><table>
    <thead><tr><th class="left">Team</th>${g.quarters[0].map((_, i) => `<th>${label(i)}</th>`).join("")}<th>Total</th></tr></thead>
    <tbody>${[g.home, g.away].map((id, s) => `<tr>
      <td class="left">${teamLink(id)}</td>${g.quarters[s].map(q => `<td>${q}</td>`).join("")}<td><b>${g.score[s]}</b></td>
    </tr>`).join("")}</tbody>
  </table></div></div>`;
}

function leaderList(key, label) {
  const min = minGames();
  const top = players.filter(p => p.gp && p.gp >= min).sort((a, b) => b[key] - a[key]).slice(0, 3);
  return `<div style="margin-bottom:10px"><div class="round-title">${label}</div>
    ${top.map((p, i) => `<div class="leader">
      <span>${i + 1}. ${esc(p.name)} <span class="muted">${esc(teamById[p.team].short)}</span></span><b>${num(p[key])}</b></div>`).join("")
      || "<span class='muted'>No games yet.</span>"}
  </div>`;
}

// ---------- Interactivity per page ----------
const setup = {
  stats() {
    let sortKey = "pts";
    const sel = document.getElementById("teamFilter");
    const box = document.getElementById("statsTable");
    const render = () => {
      const list = players.filter(p => p.gp && (!sel.value || p.team === sel.value)).sort((a, b) => b[sortKey] - a[sortKey]);
      box.innerHTML = list.length ? playerTable(list, true, false, sortKey) : "<p class='muted'>No games played yet.</p>";
      box.querySelectorAll("th.sortable").forEach(th =>
        th.addEventListener("click", () => { sortKey = th.dataset.sort; render(); }));
    };
    sel.addEventListener("change", render);
    render();
  },

  schedule() {
    const sel = document.getElementById("roundSelect");
    const teamSel = document.getElementById("schedTeam");
    const box = document.getElementById("roundGames");
    const prev = document.getElementById("prevRound");
    const next = document.getElementById("nextRound");
    sel.value = nextRound() ?? latestRound();
    const render = () => {
      const r = Number(sel.value);
      const games = GAMES.filter(g => g.round === r && (!teamSel.value || g.home === teamSel.value || g.away === teamSel.value));
      box.innerHTML = `<h2>Round ${r}</h2>` + (games.map(g => gameRow(g, true)).join("") || "<p class='muted'>No games.</p>")
        + (games.some(g => !g.score) ? "<p class='note'>Grey scores are predictions.</p>" : "");
      prev.disabled = sel.selectedIndex === 0;
      next.disabled = sel.selectedIndex === sel.options.length - 1;
    };
    prev.addEventListener("click", () => { sel.selectedIndex--; render(); });
    next.addEventListener("click", () => { sel.selectedIndex++; render(); });
    sel.addEventListener("change", render);
    teamSel.addEventListener("change", render);
    render();
  },

  predictions() {
    const h = document.getElementById("pHome"), a = document.getElementById("pAway");
    const box = document.getElementById("customPrediction");
    const render = () => {
      if (h.value === a.value) { box.innerHTML = "<p class='muted'>Choose two different teams.</p>"; return; }
      const p = predict(h.value, a.value);
      box.innerHTML = `${probBar(h.value, a.value, p.homeWin)}
        <p>Predicted score: <b>${esc(teamById[h.value].name)} ${p.homePts} – ${p.awayPts} ${esc(teamById[a.value].name)}</b></p>`;
    };
    h.addEventListener("change", render);
    a.addEventListener("change", render);
    render();
  },
};

// ---------- Router ----------
function route() {
  const [page, ...params] = (location.hash.slice(1) || "home").split("/");
  const view = pages[page];
  $app.innerHTML = view ? view(params) : notFound();
  if (view && setup[page]) setup[page](params);
  const navKey = { team: "teams", game: "schedule" }[page] || page;
  document.querySelectorAll("nav a").forEach(a => a.classList.toggle("active", a.dataset.nav === navKey));
  window.scrollTo(0, 0);
}

document.getElementById("updated").textContent = UPDATED;
window.addEventListener("hashchange", route);
document.addEventListener("DOMContentLoaded", route); // after js/betting.js has added its page
